#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6CnvM5Utz8IaE9OoXqrsxaoblT7iuWG6I5KvWQ/SSOWmln3Y45tc7+0aA5maL2gKm/PE3n3dHb8eKM6/SsxYVjMncsRZ5QVL+mf7wVI7Q3ibdNJGq7FjDrCgqaiYlDbQx96H2/ai0/QuhDMI0loRo3Of3mk8eeVL5HceaTLJGtreJdaM0Sh5vAjoTJL3+HneLBKdS2meeiVpiPF1bf8q9E9Iak6aHDToL80PFRD/5WYRH7w9wxRCyMdD7ZOBkWmK0qvSF2mPsj6ngGTVY39kMcNVwfEnpt+o+B+VOQTQUKvA4MY98PAdXZft4HlLHj5B8jhRrNKXTRea/cgwxA2br aws-key
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT+7GJtX+CrjK8wpAKWrddHlEGI7dYL9x/opjyhuexzOVJOOzJgCv5+QIACSdHUDCrdDsIdE9sj9JqvjhBouSCKBG1CeRkOwWCyR/xFq2E0t8XPsHPxkSVI4PdwQFbjnmeBindz/wQtSr6SuoZAn7LaKp6qj0ZRn+DGy5c60SmWDOXRVjLeDA+HU4Byvdtn+tyzJM4ADyng4e6lg3MaYzXk2ZBCDu7sF+HL/DucVsv+T7GXLyPX1k1xzFYEOiMBLAYvBhRZ7KaeSH7Uo1XnPAivwBF6+mirsF9M05LU3Sn2MP2d1ddXNmbZcZcBYgGSMwLKsY6+sT/pMAJq4Hkmug1wLKsY6+sT/pMAJq4Hkmug1 aws-key

ssh_pwauth: false
disable_root: true
package_update: true
packages:
  - curl
  - wget

runcmd:
  # update weil oben schon einmal gekommen
  - sudo apt install -y mariadb-server # -y weil es sonst nachfragen würde
  - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;"
  - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf
  - sudo systemctl restart mariadb.service
